name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      # The last part of the command uses $ from bash to substitute the value returned from the command inside the parethesis
      # in that spot of the code. date +%s is actually a bash command that returns the date in the given format %s
      run: docker build . --file Dockerfile --tag my-web-app:$(date +%s)
